# Generated by Django 5.0.3 on 2024-07-19 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="type",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
